config/routes.rb
Inmobiliaria::Application.routes.draw do
  resources :categorias

  get "publica/index"
  get "publica/contacto"
  get "publica/nosotros"
  
  match 'contacto' => 'publica#contacto'
  match 'nosotros' => 'publica#nosotros'

  resources :anuncios
  root :to => 'publica#index'

  
  
  

end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
	belongs_to :categoria
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
	has_many :anuncios
end

app/controllers/anuncios_controller.rb
class AnunciosController < ApplicationController
  # GET /anuncios
  # GET /anuncios.json
  def index
    @anuncios = Anuncio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @anuncios }
    end
  end

  # GET /anuncios/1
  # GET /anuncios/1.json
  def show
    @anuncio = Anuncio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @anuncio }
    end
  end

  # GET /anuncios/new
  # GET /anuncios/new.json
  def new
    @anuncio = Anuncio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @anuncio }
    end
  end

  # GET /anuncios/1/edit
  def edit
    @anuncio = Anuncio.find(params[:id])
  end

  # POST /anuncios
  # POST /anuncios.json
  def create
    @anuncio = Anuncio.new(params[:anuncio])

    respond_to do |format|
      if @anuncio.save
        format.html { redirect_to @anuncio, notice: 'Anuncio was successfully created.' }
        format.json { render json: @anuncio, status: :created, location: @anuncio }
      else
        format.html { render action: "new" }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /anuncios/1
  # PUT /anuncios/1.json
  def update
    @anuncio = Anuncio.find(params[:id])

    respond_to do |format|
      if @anuncio.update_attributes(params[:anuncio])
        format.html { redirect_to @anuncio, notice: 'Anuncio was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anuncios/1
  # DELETE /anuncios/1.json
  def destroy
    @anuncio = Anuncio.find(params[:id])
    @anuncio.destroy

    respond_to do |format|
      format.html { redirect_to anuncios_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  # GET /categorias
  # GET /categorias.json
  def index
    @categorias = Categoria.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categorias }
    end
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
    @categoria = Categoria.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categoria }
    end
  end

  # GET /categorias/new
  # GET /categorias/new.json
  def new
    @categoria = Categoria.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categoria }
    end
  end

  # GET /categorias/1/edit
  def edit
    @categoria = Categoria.find(params[:id])
  end

  # POST /categorias
  # POST /categorias.json
  def create
    @categoria = Categoria.new(params[:categoria])

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to @categoria, notice: 'Categoria was successfully created.' }
        format.json { render json: @categoria, status: :created, location: @categoria }
      else
        format.html { render action: "new" }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categorias/1
  # PUT /categorias/1.json
  def update
    @categoria = Categoria.find(params[:id])

    respond_to do |format|
      if @categoria.update_attributes(params[:categoria])
        format.html { redirect_to @categoria, notice: 'Categoria was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy
    @categoria = Categoria.find(params[:id])
    @categoria.destroy

    respond_to do |format|
      format.html { redirect_to categorias_url }
      format.json { head :ok }
    end
  end
end

app/controllers/publica_controller.rb
class PublicaController < ApplicationController
  def index
  #@noticias = Anuncio.all
  #@noticias = Anuncio.find(:all, :limit => 4, :order => "created_at DESC" )

  end

  def contacto
  end

  def nosotros
  
  end

end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/prueba_helper.rb
module PruebaHelper
end

app/helpers/publica_helper.rb
module PublicaHelper
end

app/views/anuncios/_form.html.erb
<%= form_for(@anuncio) do |f| %>
  <% if @anuncio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anuncio.errors.count, "error") %> prohibited this anuncio from being saved:</h2>

      <ul>
      <% @anuncio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class="field">
    <%= f.label :categoria %><br />
    <%= f.collection_select :categoria_id, Categoria.all, :id, :nombre %>
  </div>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br />
    <%= f.text_area :contenido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anuncios/edit.html.erb
<h1>Editing anuncio</h1>

<%= render 'form' %>

<%= link_to 'Show', @anuncio %> |
<%= link_to 'Back', anuncios_path %>

app/views/anuncios/index.html.erb
<h1>Anuncios</h1>

<table>
  <tr>
  	<th width="50">ID</th>
    <th width="150">Titulo</th>
    <th width="250">Contenido</th>
    <th width="50"></th>
    <th width="50"></th>
    <th width="50"></th>
  </tr>

<% @anuncios.each do |anuncio| %>
  <tr>
  	<td><%= anuncio.id %></td>
    <td><%= anuncio.titulo %></td>
    <td><%= anuncio.contenido %></td>
    <td><%= link_to 'Show', anuncio %></td>
    <td><%= link_to 'Edit', edit_anuncio_path(anuncio) %></td>
    <td><%= link_to 'Destroy', anuncio, confirm: 'Estas seguro que deseas borrar?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Anuncio', new_anuncio_path %>

app/views/anuncios/new.html.erb
<h1>New anuncio</h1>

<%= render 'form' %>

<%= link_to 'Back', anuncios_path %>

app/views/anuncios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @anuncio.titulo %>
</p>

<p>
  <b>Contenido:</b>
  <%= @anuncio.contenido %>
</p>


<%= link_to 'Edit', edit_anuncio_path(@anuncio) %> |
<%= link_to 'Back', anuncios_path %>

app/views/categorias/_form.html.erb
<%= form_for(@categoria) do |f| %>
  <% if @categoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria.errors.count, "error") %> prohibited this categoria from being saved:</h2>

      <ul>
      <% @categoria.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categorias/edit.html.erb
<h1>Editing categoria</h1>

<%= render 'form' %>

<%= link_to 'Show', @categoria %> |
<%= link_to 'Back', categorias_path %>

app/views/categorias/index.html.erb
<h1>Listing categorias</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categorias.each do |categoria| %>
  <tr>
    <td><%= categoria.nombre %></td>
    <td><%= link_to 'Show', categoria %></td>
    <td><%= link_to 'Edit', edit_categoria_path(categoria) %></td>
    <td><%= link_to 'Destroy', categoria, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Categoria', new_categoria_path %>

app/views/categorias/new.html.erb
<h1>New categoria</h1>

<%= render 'form' %>

<%= link_to 'Back', categorias_path %>

app/views/categorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @categoria.nombre %>
</p>

<% for anuncio in @categoria.anuncios %>
	<%= link_to anuncio.titulo, anuncio %><br>

<% end %>

<%= link_to 'Edit', edit_categoria_path(@categoria) %> |
<%= link_to 'Back', categorias_path %>

app/views/compartido/_ultimas_noticias.html.erb
<h3> Últimas Noticias</h3>

  	<% @noticias = Anuncio.find(:all, :limit => 4, :order => "created_at DESC" )%>
<ul>
<% @noticias.each do |noticia| %>
	<li>
	<b><%= link_to noticia.titulo, noticia %></b><br>
	<%= noticia.created_at.strftime("%e-%m-%Y") %><br>
	
	<% if !noticia.categoria.blank? %>
	<i><%= link_to noticia.categoria.nombre, noticia.categoria %></i><br>
	
	<% end %>
	
	<%= noticia.contenido.truncate(140, :omission => "... ") %>
	<%= link_to "Leer Mas", noticia %>
	<br>
	</li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inmobiliaria</title>
  <%= stylesheet_link_tag    "application", "estilo" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="contenedor">
	<div id="header">
		<div id="logo">
			<%= link_to (image_tag "logo.jpg", :size=>"200x150"), root_path %>
		</div>
		<div id="titulo">
			<h1>Inmobiliaria</h1>
		</div>
		<div id="btns">
			
			<%= link_to "Noticias", anuncios_path %>
			<%= link_to "Nosotros", nosotros_path %>
			<%= link_to "Categorias", categorias_path %>
			<%= link_to "Contacto", contacto_path %>
		</div>
	</div>
</div>

<%= yield %>
</div>
</body>
</html>

app/views/publica/contacto.html.erb
<h1>Publica#contacto</h1>
<p>Find me in app/views/publica/contacto.html.erb</p>

app/views/publica/index.html.erb
<h1>Publica#index</h1>
<p>Find me in app/views/publica/index.html.erb</p>

<%= render "/compartido/ultimas_noticias"%>

app/views/publica/nosotros.html.erb
<h1>Publica#nosotros</h1>
<p>Find me in app/views/publica/nosotros.html.erb</p>

<%= render "/compartido/ultimas_noticias"%>